# Form implementation generated from reading ui file 'stat418.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import string
from PySide6 import QtCore, QtWidgets

class Ui_SpellCheck(object):
    def setupUi(self, SpellCheck):
        f = open("words_large.txt", "r")
        self.words = f.read()

        print( self.words[0:40] )
        SpellCheck.setObjectName("SpellCheck")
        SpellCheck.resize(800, 500)
        SpellCheck.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget = QtWidgets.QWidget(parent=SpellCheck)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 500))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 24, 700, 450))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.textEdit = QtWidgets.QTextEdit(parent=self.verticalLayoutWidget)
        self.textEdit.setMaximumSize(QtCore.QSize(519, 53))
        self.textEdit.setObjectName("textEdit")
        self.textEdit.textChanged.connect(self.textEntered)
        self.verticalLayout_3.addWidget(self.textEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_3.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.verticalLayoutWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        SpellCheck.setCentralWidget(self.centralwidget)

        self.retranslateUi(SpellCheck)
        QtCore.QMetaObject.connectSlotsByName(SpellCheck)

        
    def retranslateUi(self, SpellCheck):
        _translate = QtCore.QCoreApplication.translate
        SpellCheck.setWindowTitle(_translate("SpellCheck", "SpellCheck"))
        self.textEdit.setHtml(_translate("SpellCheck", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter a sentence here</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("SpellCheck", "Current Word: here"))
        self.label_2.setText(_translate("SpellCheck", "Dictionary match"))

        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("SpellCheck", "Suggestion 1"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("SpellCheck", "Suggestion 2"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("SpellCheck", "Suggestion 3"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("SpellCheck", "Suggestion 4 "))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("SpellCheck", "Suggestion 5"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("SpellCheck", "Suggestion 6"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("SpellCheck", "Suggestion 7"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("SpellCheck", "Suggestion 8"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SpellCheck", "Error"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SpellCheck", "Correction"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SpellCheck", "Correct Letter"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SpellCheck", "Error Letter"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("SpellCheck", "Position "))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("SpellCheck", "Type"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)


    def textEntered(self):
        _translate = QtCore.QCoreApplication.translate

        noPunctuation = self.textEdit.toPlainText().strip().translate(str.maketrans('','',string.punctuation))
        currentWord = noPunctuation.rpartition(" ")[2]
        
        inDictionary = self.words.find( '\n' + currentWord.lower()+ '\n') != -1
        self.label.setText(_translate("SpellCheck", "Current word: " + currentWord))
        self.label_2.setText(_translate("SpellCheck", "Dictionary Match" if inDictionary else "No Dictionary Match"))
        
